services:
  - docker
install:
  - docker build -t jturpin/dfievents .
  - docker run -d -p 127.0.0.1:80:80 --name dfievent jturpin/dfievents
script:
  - docker ps | grep -q dfievents  
  - curl 127.0.0.1:80 | grep "DFI Events is a Colorado"
notifications:
  webhooks: 
    urls:
      - http://your-domain.com/notifications
    on_success: always
