---
title: "About"
date: 2021-08-12T16:30:19-06:00
draft: false
---

#About DFI Events

DFI Events, was established in 2003 by husband and wife team, Leslie Dietz and Kevin Farrell. The two of them, separately and together, have over 40 years of experience in the hospitality industry. Having met in Australia, Irish-born Kevin and Colorado native Leslie moved to the United States to further their careers in the event management world. Since 2003, DFI Events has planned and operated more than 100 domestic and international events from their Steamboat Springs, Colorado headquarters
